name: sclitr

channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - anndata=0.11.1
  - h5py=3.12.1
  - hdf5=1.14.3
  - ipykernel=6.29.5
  - ipython=8.27.0
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - leidenalg=0.10.2
  - libleidenalg=0.11.1
  - loompy=2.0.16
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.6
  - mudata=0.3.1
  - muon=0.1.6
  - numba=0.60.0
  - numpy=1.24.3
  - pandas=2.2.2
  - pip=24.2
  - python=3.11.10
  - scanpy=1.10.3
  - scikit-image=0.24.0
  - scikit-learn=1.5.1
  - scipy=1.14.1
  - scvelo=0.2.5
  - seaborn=0.13.2
  - sqlite=3.47.0
  - tqdm=4.66.5
  - umap-learn=0.5.7
  - cython=0.29.32
  - gcc_linux-64
  - pip:
      - harmonypy==0.0.10
      - click==8.1.3
      - matplotlib-venn==1.1.2
      - sclitr==0.1.4
      - symphonypy==0.2.1
      - sympy==1.13.1
      - velocyto==0.17.17
      - venny4py==1.0.3
